# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'SwiftUI Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftUI Example
pod 'ScreenShield', :path => '../'

end

target 'UIKit Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UIKit Example
pod 'ScreenShield', :path => '../'

end


